package vuelosavion;

import java.awt.Color;
import java.awt.Label;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author: Cristian Gallego 
 * Codigo: 1.112.630.610
 */
public class MenuPrincipal extends javax.swing.JFrame {

    public Avion avion = new Avion();
    int PorcentajeOcupacion = 0;
    Label[] puesto;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        puesto = new Label[50];
        puesto[0] = label1;
        puesto[1] = label2;
        puesto[2] = label3;
        puesto[3] = label4;
        puesto[4] = label5;
        puesto[5] = label6;
        puesto[6] = label7;
        puesto[7] = label8;
        puesto[8] = label9;
        puesto[9] = label10;
        puesto[10] = label11;
        puesto[11] = label12;
        puesto[12] = label13;
        puesto[13] = label14;
        puesto[14] = label15;
        puesto[15] = label16;
        puesto[16] = label17;
        puesto[17] = label18;
        puesto[18] = label19;
        puesto[19] = label20;
        puesto[20] = label21;
        puesto[21] = label22;
        puesto[22] = label23;
        puesto[23] = label24;
        puesto[24] = label25;
        puesto[25] = label26;
        puesto[26] = label27;
        puesto[27] = label28;
        puesto[28] = label29;
        puesto[29] = label30;
        puesto[30] = label31;
        puesto[31] = label32;
        puesto[32] = label33;
        puesto[33] = label34;
        puesto[34] = label35;
        puesto[35] = label36;
        puesto[36] = label37;
        puesto[37] = label38;
        puesto[38] = label39;
        puesto[39] = label40;
        puesto[40] = label41;
        puesto[41] = label42;
        puesto[42] = label43;
        puesto[43] = label44;
        puesto[44] = label45;
        puesto[45] = label46;
        puesto[46] = label47;
        puesto[47] = label48;
        puesto[48] = label49;
        puesto[49] = label50;

    }

    public String[] getPosicion(String Clase) {

        String[] Posicion = new String[4];
        if ("Ejecutiva".equals(Clase)) {
            Posicion[0] = "Seleccione..";
            Posicion[1] = "Ventana";
            Posicion[2] = "Pasillo";
        } else if ("Economica".equals(Clase)) {
            Posicion[0] = "Seleccione..";
            Posicion[1] = "Ventana";
            Posicion[2] = "Centro";
            Posicion[3] = "Pasillo";
        }
        return Posicion;
    }

    public String[] getSillas(String Clase, String Posicion) {
        int tamDisponibilidad = 0;
        String[] sillon = new String[49];
        for (int i = 0; i <= 49; i++) {
            if (avion.silla[i].disponibilidad == true && avion.silla[i].clase.equals(Clase) && avion.silla[i].posicion.equals(Posicion)) {
                sillon[tamDisponibilidad] = String.valueOf(avion.silla[i].numero);
                tamDisponibilidad += 1;
            }
        }
        return sillon;

    }

    public Avion getAvion() {
        return avion;
    }

    public void setAvion(Avion avion) {
        this.avion = avion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBoxClase = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jBoxPosicion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBoxSilla = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        label31 = new java.awt.Label();
        label32 = new java.awt.Label();
        label33 = new java.awt.Label();
        label34 = new java.awt.Label();
        label35 = new java.awt.Label();
        label36 = new java.awt.Label();
        label37 = new java.awt.Label();
        label38 = new java.awt.Label();
        label39 = new java.awt.Label();
        label40 = new java.awt.Label();
        label41 = new java.awt.Label();
        label42 = new java.awt.Label();
        label43 = new java.awt.Label();
        label44 = new java.awt.Label();
        label45 = new java.awt.Label();
        label46 = new java.awt.Label();
        label47 = new java.awt.Label();
        label48 = new java.awt.Label();
        label49 = new java.awt.Label();
        label50 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabelPorcentajeO = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabelNom = new javax.swing.JLabel();
        jLabelClas = new javax.swing.JLabel();
        jLabelPos = new javax.swing.JLabel();
        jLabelSi = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelClase = new javax.swing.JLabel();
        jLabelPosicion = new javax.swing.JLabel();
        jLabelSilla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setToolTipText("");
        jPanel1.setName("Reservas"); // NOI18N

        jLabel2.setText("Nombres");

        jLabel3.setText("Cedula");

        jLabel4.setText("Clase");

        jBoxClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -", "Economica", "Ejecutiva" }));
        jBoxClase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxClaseItemStateChanged(evt);
            }
        });
        jBoxClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxClaseActionPerformed(evt);
            }
        });

        jLabel5.setText("Posición de Silla");

        jBoxPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -" }));
        jBoxPosicion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxPosicionItemStateChanged(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/air2_1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setText(" Silla");

        jBoxSilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccione -" }));
        jBoxSilla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jBoxSillaItemStateChanged(evt);
            }
        });
        jBoxSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxSillaActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor del vuelo");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelPrecio.setText("0 $");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel11.setText("Presentado por :  Cristian C Gallego Rangel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre)
                            .addComponent(txtCedula)
                            .addComponent(jBoxClase, 0, 163, Short.MAX_VALUE)
                            .addComponent(jBoxPosicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBoxSilla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(805, 805, 805)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jBoxSilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jBoxClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jBoxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Registrar Pasajeros", jPanel1);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        label1.setBackground(new java.awt.Color(153, 153, 153));
        label1.setText("  ");
        jPanel4.add(label1);
        label1.setBounds(340, 90, 20, 20);

        label2.setBackground(new java.awt.Color(153, 153, 153));
        label2.setText("  ");
        jPanel4.add(label2);
        label2.setBounds(370, 90, 20, 20);

        label3.setBackground(new java.awt.Color(153, 153, 153));
        label3.setText("  ");
        jPanel4.add(label3);
        label3.setBounds(440, 90, 20, 20);

        label4.setBackground(new java.awt.Color(153, 153, 153));
        label4.setText("  ");
        jPanel4.add(label4);
        label4.setBounds(470, 90, 20, 20);

        label5.setBackground(new java.awt.Color(153, 153, 153));
        label5.setText("  ");
        jPanel4.add(label5);
        label5.setBounds(340, 120, 20, 20);

        label6.setBackground(new java.awt.Color(153, 153, 153));
        label6.setText("  ");
        jPanel4.add(label6);
        label6.setBounds(370, 120, 20, 20);

        label7.setBackground(new java.awt.Color(153, 153, 153));
        label7.setText("  ");
        jPanel4.add(label7);
        label7.setBounds(440, 120, 20, 20);

        label8.setBackground(new java.awt.Color(153, 153, 153));
        label8.setText("  ");
        jPanel4.add(label8);
        label8.setBounds(470, 120, 20, 20);

        label9.setBackground(new java.awt.Color(153, 153, 153));
        label9.setText("  ");
        jPanel4.add(label9);
        label9.setBounds(320, 160, 20, 20);

        label10.setBackground(new java.awt.Color(153, 153, 153));
        label10.setText("  ");
        jPanel4.add(label10);
        label10.setBounds(350, 160, 20, 20);

        label11.setBackground(new java.awt.Color(153, 153, 153));
        label11.setText("  ");
        jPanel4.add(label11);
        label11.setBounds(380, 160, 20, 20);

        label12.setBackground(new java.awt.Color(153, 153, 153));
        label12.setText("  ");
        jPanel4.add(label12);
        label12.setBounds(430, 160, 20, 20);

        label13.setBackground(new java.awt.Color(153, 153, 153));
        label13.setText("  ");
        jPanel4.add(label13);
        label13.setBounds(460, 160, 20, 20);

        label14.setBackground(new java.awt.Color(153, 153, 153));
        label14.setText("  ");
        jPanel4.add(label14);
        label14.setBounds(490, 160, 20, 20);

        label15.setBackground(new java.awt.Color(153, 153, 153));
        label15.setText("  ");
        jPanel4.add(label15);
        label15.setBounds(320, 190, 20, 20);

        label16.setBackground(new java.awt.Color(153, 153, 153));
        label16.setText("  ");
        jPanel4.add(label16);
        label16.setBounds(350, 190, 20, 20);

        label17.setBackground(new java.awt.Color(153, 153, 153));
        label17.setText("  ");
        jPanel4.add(label17);
        label17.setBounds(380, 190, 20, 20);

        label18.setBackground(new java.awt.Color(153, 153, 153));
        label18.setText("  ");
        jPanel4.add(label18);
        label18.setBounds(430, 190, 20, 20);

        label19.setBackground(new java.awt.Color(153, 153, 153));
        label19.setText("  ");
        jPanel4.add(label19);
        label19.setBounds(460, 190, 20, 20);

        label20.setBackground(new java.awt.Color(153, 153, 153));
        label20.setText("  ");
        jPanel4.add(label20);
        label20.setBounds(490, 190, 20, 20);

        label21.setBackground(new java.awt.Color(153, 153, 153));
        label21.setText("  ");
        jPanel4.add(label21);
        label21.setBounds(320, 220, 20, 20);

        label22.setBackground(new java.awt.Color(153, 153, 153));
        label22.setText("  ");
        jPanel4.add(label22);
        label22.setBounds(350, 220, 20, 20);

        label23.setBackground(new java.awt.Color(153, 153, 153));
        label23.setText("  ");
        jPanel4.add(label23);
        label23.setBounds(380, 220, 20, 20);

        label24.setBackground(new java.awt.Color(153, 153, 153));
        label24.setText("  ");
        jPanel4.add(label24);
        label24.setBounds(430, 220, 20, 20);

        label25.setBackground(new java.awt.Color(153, 153, 153));
        label25.setText("  ");
        jPanel4.add(label25);
        label25.setBounds(460, 220, 20, 20);

        label26.setBackground(new java.awt.Color(153, 153, 153));
        label26.setText("  ");
        jPanel4.add(label26);
        label26.setBounds(490, 220, 20, 20);

        label27.setBackground(new java.awt.Color(153, 153, 153));
        label27.setText("  ");
        jPanel4.add(label27);
        label27.setBounds(320, 250, 20, 20);

        label28.setBackground(new java.awt.Color(153, 153, 153));
        label28.setText("  ");
        jPanel4.add(label28);
        label28.setBounds(350, 250, 20, 20);

        label29.setBackground(new java.awt.Color(153, 153, 153));
        label29.setText("  ");
        jPanel4.add(label29);
        label29.setBounds(380, 250, 20, 20);

        label30.setBackground(new java.awt.Color(153, 153, 153));
        label30.setText("  ");
        jPanel4.add(label30);
        label30.setBounds(430, 250, 20, 20);

        label31.setBackground(new java.awt.Color(153, 153, 153));
        label31.setText("  ");
        jPanel4.add(label31);
        label31.setBounds(460, 250, 20, 20);

        label32.setBackground(new java.awt.Color(153, 153, 153));
        label32.setText("  ");
        jPanel4.add(label32);
        label32.setBounds(490, 250, 20, 20);

        label33.setBackground(new java.awt.Color(153, 153, 153));
        label33.setText("  ");
        jPanel4.add(label33);
        label33.setBounds(320, 280, 20, 20);

        label34.setBackground(new java.awt.Color(153, 153, 153));
        label34.setText("  ");
        jPanel4.add(label34);
        label34.setBounds(350, 280, 20, 20);

        label35.setBackground(new java.awt.Color(153, 153, 153));
        label35.setText("  ");
        jPanel4.add(label35);
        label35.setBounds(380, 280, 20, 20);

        label36.setBackground(new java.awt.Color(153, 153, 153));
        label36.setText("  ");
        jPanel4.add(label36);
        label36.setBounds(430, 280, 20, 20);

        label37.setBackground(new java.awt.Color(153, 153, 153));
        label37.setText("  ");
        jPanel4.add(label37);
        label37.setBounds(460, 280, 20, 20);

        label38.setBackground(new java.awt.Color(153, 153, 153));
        label38.setText("  ");
        jPanel4.add(label38);
        label38.setBounds(490, 280, 20, 20);

        label39.setBackground(new java.awt.Color(153, 153, 153));
        label39.setText("  ");
        jPanel4.add(label39);
        label39.setBounds(320, 310, 20, 20);

        label40.setBackground(new java.awt.Color(153, 153, 153));
        label40.setText("  ");
        jPanel4.add(label40);
        label40.setBounds(350, 310, 20, 20);

        label41.setBackground(new java.awt.Color(153, 153, 153));
        label41.setText("  ");
        jPanel4.add(label41);
        label41.setBounds(380, 310, 20, 20);

        label42.setBackground(new java.awt.Color(153, 153, 153));
        label42.setText("  ");
        jPanel4.add(label42);
        label42.setBounds(430, 310, 20, 20);

        label43.setBackground(new java.awt.Color(153, 153, 153));
        label43.setText("  ");
        jPanel4.add(label43);
        label43.setBounds(460, 310, 20, 20);

        label44.setBackground(new java.awt.Color(153, 153, 153));
        label44.setText("  ");
        jPanel4.add(label44);
        label44.setBounds(490, 310, 20, 20);

        label45.setBackground(new java.awt.Color(153, 153, 153));
        label45.setText("  ");
        jPanel4.add(label45);
        label45.setBounds(320, 340, 20, 20);

        label46.setBackground(new java.awt.Color(153, 153, 153));
        label46.setText("  ");
        jPanel4.add(label46);
        label46.setBounds(350, 340, 20, 20);

        label47.setBackground(new java.awt.Color(153, 153, 153));
        label47.setText("  ");
        jPanel4.add(label47);
        label47.setBounds(380, 340, 20, 20);

        label48.setBackground(new java.awt.Color(153, 153, 153));
        label48.setText("  ");
        jPanel4.add(label48);
        label48.setBounds(430, 340, 20, 20);

        label49.setBackground(new java.awt.Color(153, 153, 153));
        label49.setText("  ");
        jPanel4.add(label49);
        label49.setBounds(460, 340, 20, 20);

        label50.setBackground(new java.awt.Color(153, 153, 153));
        label50.setText("  ");
        jPanel4.add(label50);
        label50.setBounds(490, 340, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Avion.jpg"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(140, 20, 557, 450);

        jLabelPorcentajeO.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabelPorcentajeO.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPorcentajeO.setText("       0 %");
        jPanel4.add(jLabelPorcentajeO);
        jLabelPorcentajeO.setBounds(760, 50, 270, 210);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Avión", jPanel3);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("Buscar Pasajero");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cedula");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNom.setText("Nombre");

        jLabelClas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelClas.setText("Clase");

        jLabelPos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPos.setText("Posicion Silla");

        jLabelSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSi.setText("Silla");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelClas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSilla)
                                            .addComponent(txttCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabelPosicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                                .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabelClase, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelSi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCancelar)))
                                .addGap(36, 36, 36)
                                .addComponent(btnBuscar))
                            .addComponent(jLabelPos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSilla)
                    .addComponent(jLabelSi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addGap(144, 144, 144))
        );

        jTabbedPane1.addTab("Buscar Pasajero", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoxSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxSillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxSillaActionPerformed

    private void jBoxClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxClaseActionPerformed

    private void jBoxClaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxClaseItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.jBoxPosicion.setModel(new DefaultComboBoxModel(this.getPosicion(this.jBoxClase.getSelectedItem().toString())));
        }

    }//GEN-LAST:event_jBoxClaseItemStateChanged

    private void jBoxPosicionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxPosicionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.jBoxSilla.setModel(new DefaultComboBoxModel(this.getSillas((this.jBoxClase.getSelectedItem().toString()),
                    this.jBoxPosicion.getSelectedItem().toString())));
        }
    }//GEN-LAST:event_jBoxPosicionItemStateChanged

    private void jBoxSillaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jBoxSillaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int p = Integer.parseInt(this.jBoxSilla.getSelectedItem().toString());
            int precio = avion.silla[p - 1].getPrecio();
            this.jLabelPrecio.setText(String.valueOf(precio));
        }
    }//GEN-LAST:event_jBoxSillaItemStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // Recibimos los parametros que nos ingresan por pantalla.
        String Nombre = txtNombre.getText();
        String Cedula = txtCedula.getText();
        System.out.println(Nombre);
        System.out.println(Cedula);
        int Numero = Integer.parseInt((String) jBoxSilla.getSelectedItem());
        Pasajero pasajero = new Pasajero();
        pasajero.setNombre(Nombre);
        pasajero.setCedula(Cedula);
        avion.silla[Numero - 1].disponibilidad = false;
        avion.silla[Numero - 1].setPasajero(pasajero);
        System.out.println(avion);
        System.out.println(pasajero);
        txtNombre.setText("");
        txtCedula.setText("");
        jBoxClase.setSelectedIndex(0);
        jBoxPosicion.removeAllItems();
        jBoxSilla.removeAllItems();
        String PorDisponible = String.valueOf((Ocupacion() * 100) / 50) + "%";
        jLabelPorcentajeO.setText(PorDisponible);
        jLabelPrecio.setText("0$");


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String Cedula = txttCedula.getText();
        Pasajero pasajero = new Pasajero();
        boolean Encontrado = false;
        for (int i = 0; i <= 49; i++) {
            pasajero = avion.silla[i].getPasajero();
            String BuscaCedula = avion.silla[i].getPasajero().getCedula();
            if (BuscaCedula == null ? Cedula == null : BuscaCedula.equals(Cedula)) {
                String Nombre = avion.silla[i].getPasajero().getNombre();
                System.out.println(Nombre);
                String Clase = avion.silla[i].getClase();
                String Posicion = avion.silla[i].getPosicion();
                String Numero = String.valueOf(avion.silla[i].getNumero());
                jLabelNombre.setText(Nombre);
                jLabelClase.setText(Clase);
                jLabelPosicion.setText(Posicion);
                jLabelSilla.setText(Numero);
                Encontrado = true;

            }

        }
        if (!Encontrado) {
            JOptionPane.showMessageDialog(null, " No realizaste ninguna reserva ");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txttCedula.setText("");
        jLabelNombre.setText("");
        jLabelClase.setText("");
        jLabelPosicion.setText("");
        jLabelSilla.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String Cedula = txttCedula.getText();
        Pasajero pasajero = new Pasajero();
        boolean Eliminar = false;
        for(int i=0;i<=49;i++)
        {
            pasajero = avion.silla[i].getPasajero(); 
            String BuscaCedula = avion.silla[i].getPasajero().getCedula();
            if( BuscaCedula == null ? Cedula == null : BuscaCedula.equals(Cedula))
            {                   
             pasajero.setNombre(" ");
             pasajero.setCedula(" ");
             avion.silla[i].setPasajero(pasajero);
             avion.silla[i].setDisponibilidad(true);
             Eliminar = true;
            }
        }
    txttCedula.setText("");    
    jLabelNombre.setText("");
    jLabelClase.setText("");
    jLabelPosicion.setText("");
    jLabelSilla.setText("");  
    if(Eliminar)
    {
     JOptionPane.showMessageDialog(null, " Se ha eliminado la reserva");    
    }
      String PorDisponible = String.valueOf((Ocupacion()*100)/50)+"%";
      jLabelPorcentajeO.setText(PorDisponible);     
                                     
    }//GEN-LAST:event_btnEliminarActionPerformed

    public int Ocupacion() {
        int CuentaSillascupadas = 0;
        for (int i = 0; i <= 49; i++) {
            if (avion.silla[i].isDisponibilidad() == false) {
                puesto[i].setBackground(Color.RED);
                CuentaSillascupadas++;
            } else {
                puesto[i].setBackground(Color.CYAN);
            }
        }
        return CuentaSillascupadas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> jBoxClase;
    private javax.swing.JComboBox<String> jBoxPosicion;
    private javax.swing.JComboBox<String> jBoxSilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClas;
    private javax.swing.JLabel jLabelClase;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPorcentajeO;
    private javax.swing.JLabel jLabelPos;
    private javax.swing.JLabel jLabelPosicion;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelSi;
    private javax.swing.JLabel jLabelSilla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label3;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label4;
    private java.awt.Label label40;
    private java.awt.Label label41;
    private java.awt.Label label42;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label45;
    private java.awt.Label label46;
    private java.awt.Label label47;
    private java.awt.Label label48;
    private java.awt.Label label49;
    private java.awt.Label label5;
    private java.awt.Label label50;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txttCedula;
    // End of variables declaration//GEN-END:variables
}
